apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex-media-server.fullname" . }}
  labels:
    {{- include "plex-media-server.labels" . | nindent 4 }}
{{- with .Values.service.labels }}
    {{ toYaml . | indent 6 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plex-media-server.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
